/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MatchCard: typeof import('./src/components/match/MatchCard.vue')['default']
    MatchList: typeof import('./src/components/match/MatchList.vue')['default']
  }
}
